version: "3.9"
services:
  postgres:
    build:
      context: ./src/main/java/com/gremio/postgres/.
    container_name: gremio_postgres
    restart: unless-stopped
    networks:
      - gremio
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: gremio
      POSTGRES_USER: gremio
    volumes:
      - psql_gremio:/var/lib/postgresql/data
      - gremio_psql_logs:/logs/postgres
    command: postgres -c config_file=/etc/postgresql/postgresql.conf


networks:
  gremio:
    external: true
volumes:
  psql_gremio:
  gremio_psql_logs: